# Generated by Django 5.2 on 2025-05-18 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findjob', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
