# Generated by Django 5.2 on 2025-05-18 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findjob', '0002_alter_job_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='details',
            field=models.TextField(blank=True),
        ),
    ]
