# Generated by Django 5.2 on 2025-05-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findjob', '0004_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='rate_type',
            field=models.CharField(choices=[('hr', 'Per Hour'), ('day', 'Per Day')], default='hr', max_length=10),
            preserve_default=False,
        ),
    ]
