# Generated by Django 5.2 on 2025-05-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findjob', '0005_job_rate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='city',
            field=models.CharField(default='Quezon', max_length=100),
        ),
    ]
