# Generated by Django 5.2 on 2025-05-22 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findjob', '0007_application_status'),
        ('findjob', '0007_job_employer'),
    ]

    operations = [
    ]
