# Generated by Django 5.2 on 2025-05-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_category_workerprofile_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='location',
            field=models.TextField(blank=True),
        ),
    ]
